---
dependency:
  name: galaxy
#ansible:
  #inventory_file: ../../../../qa
  #diff: False
  #become: True
  #vault_password_file: ../../../../.vault
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance-centos
    image: centos:7
    privileged: true
    command: /usr/lib/systemd/systemd
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    i: ../../../qa
  inventory:
    group_vars:
      all:
        ansible_host: test
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
